#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/../../.." && pwd)"

CHECKPOINT="${CHECKPOINT:-${ROOT_DIR}/nn/models/samples/best_model.pt}"
PROTEIN="${PROTEIN:-MESVEKKDSLTAPSEFATTASTDAANAPTTFPVEAPPLEEEEVIIEQDPGFVSEDDEDRSVPTEDKKQDQDNAEANEEQVGRGDERHGDYLDVGDDVLLKHLQRQCAIICDALQERSDVPLAIADVSLAYERHLFSPRVPPKRQENGTCEPNPRLNFYPVFAVPEVLATYHIFFQNCKIPLSCRANRSRADKQLALRQGAVIPDIASLNEVPKIFEGLGRDEKRAANALQQENSENESHSGVLVELEGDNARLAVLKRSIEVTHFAYPALNLPPKVMSTVMSELIVRRAQPLERDANLQEQTEEGLPAVGDEQLARWLQTREPADLEERRKLMMAAVLVTVELECMQRFFADPEMQRKLEETLHYTFRQGYVRQACKISNVELCNLVSYLGILHENRLGQNVLHSTLKGEARRDYVRDCVYLFLCYTWQTAMGVWQQCLEECNLKELQKLLKQNLKDLWTAFNERSVAAHLADIIFPERLLKTLQQGLPDFTSQSMLQNFRNFILERSGILPATCCALPSDFVPIKYRECPPPLWGHCYLLQLANYLAYHSDIMEDVSGDGLLECHCRCNLCTPHRSLVCNSQLLNESQIIGTFELQGPSPDEKSAAPGLKLTPGLWTSAYLRKFVPEDYHAHEIRFYEDQSRPPNAELTACVITQGHILGQLQAINKARQEFLLRKGRGVYLDPQSGEELNPIPPPPQPYQQQPRALASQDGTQKEAAAAAATHGRGGILGQSGRGGFGRGGGGHDGRLGEPRRGSFRGRRGVRRNTVTLGRIPLAGAPEIGNRFQHGYNLRSSGAAGTARSPTQP}"
PEPTIDE="${PEPTIDE:-EFATTASTDAANAPTTFPVEAPPLEEEEVI}"
ALIGN_START="${ALIGN_START:-14}"
ALIGN_STOP="${ALIGN_STOP:-44}"
MODEL_NAME="${MODEL_NAME:-esm2_t6_8M_UR50D}"

ENV_DIR="${ROOT_DIR}/venv"
source "${ENV_DIR}/Scripts/activate"

cd "${ROOT_DIR}"

python3 -m nn.pred.prediction_cli \
    "$CHECKPOINT" \
    "$PROTEIN" \
    "$PEPTIDE" \
    --align-start "$ALIGN_START" \
    --align-stop "$ALIGN_STOP" \
    --model-name "$MODEL_NAME" \
    --log-json
